const DATA = [
  {
    id: 0,
    title: "Boîte avec couvercle",
    price: 350,
    desc: "Boîte avec couvercle, 3 pièces Les variations naturelles de couleur du jonc de mer donnent à chaque panier son aspect unique.Chaque boîte a été fabriquée à la main, ce qui la rend unique.Dimensions:– 1 pièce diamètre 10 cm, H6 cm;– 1 pièce diamètre 15 cm, H8 cm;– 1 pièce diamètre 20 cm, H10 cm.",
    img: "/assets/images/products/img1.jpg",
  },
  {
    id: 1,
    title: "Étagère -Blanc – L60 x P20 x H160 cm",
    price: 550,
    desc: "Couleur : blanc Matière : panneaux MDF Dimensions : L60 x P20 x H160 cm",
    img: "/assets/images/products/img5.jpg",
  },
  {
    id: 2,
    title: "Vélo Panier De Fleurs",
    price: 150,
    desc: "Vélo Panier De Fleurs Pour la décoration de la maison, les arrangements de mariage, les arrangements de fête, et la décoration de scène, décoration de table, etc. Matériel: Rotin et plastique Taille: 23cm (longueur totale) 12,5cm (panier de fleurs diamètre)9cm (hauteur du panier)1 x panier de design pour vélo",
    img: "/assets/images/products/img2.jpg",
  },
  {
    id: 3,
    title: "Horloge Murale PLATINET SUNSET",
    price: 250,
    desc: "Horloge Murale PLATINET SUNSET – 12 cadres photo – Grand nombre – Matériel: Plastique de haute qualité – Alimentation: 1 x pile AA.",
    img: "/assets/images/products/img3.jpg",
  },
  {
    id: 4,
    title: "lampe tripiers Scandinave",
    price: 1050,
    desc: "lampe tripiers Scandinave Matière : Bois /Longueur : 20 cm / Largeur : 20 cm /Hauteur : 45.5 cm.",
    img: "/assets/images/products/img4.jpg",
  },
  {
    id: 5,
    title: "Applique s",
    price: 50,
    desc: "Longueur : 25cm, Largeur: 25 cm, Profondeur: 8,5 cm",
    img: "/assets/images/products/Applique_S.jpg"
    
  },
  {
    id: 6,
    catégorie: "Lustre",
    title: "LUSTRE CER",
    desc: "Hauteur: 30 cm, D: 20cm",
    img: "/assets/images/products/lustre-cer.jpg",
    price: 40,
  },
  {
    id: 7,
    Catégorie: "Lustre",
    title: "Lustre DAM",
    desc: " Hauteur : 44 cm, Largeur : 33 cm, Profondeur : 26 cm",
    img: "/assets/images/products/lustre.jpg",
    price: 38,
  },
  {
    id: 8,
    title: "Lustre en MDF avec motif personnalisable",
    price: 45,
    desc: "Hauteur : 33 cm, Largeur : 17 cm, Profondeur : 20 cm",
    img: "/assets/images/products/lustre-en-mdf.jpg",
    
  },
  {
    id: 9,
    catégorie: "Porte Bijoux",
    title: "PORTE BIJOUX ARBRE",
    desc: "Porte Bijoux Arbre en MDF, Hauteur: 25cm, Largeur: 15 cm    ",
    img: "/assets/images/products/porte-bijoux.jpeg",
    price: 20,
  },
  {
    id: 10,
    title: "PORTE BIJOUX CHAT",
    desc: "Porte Bijoux chat en MDF, Hauteur: 27 cm, Largeur: 28 cm",
    img: "/assets/images/products/porte-bijoux-chat.jpeg",
    price: 23,
  },
  {
    id: 11,
    title: "Porte Carte",
    desc: "Porte Carte en cuir de vachette",
    img: "/assets/images/products/Porte-carte-scaled.jpg",
    price: 15,
  },
  {
    id: 12,
    catégorie: "Porte Passeport",
    title: "PORTE PASSEPORT",
    desc: "Porte Passeport avec possibilité de personnalisation. La couture de ce produit est fait main ce qui augmente sa valeur.",
    img: "/assets/images/products/Porte-passeport-scaled.jpg",
    price: 40,
  },
  {
    id: 13,
    catégorie: "Sac à main",
    title: "SAC À MAIN",
    desc: "Sac à main en Cuir de vachette pour femme de haute qualité avec une couture fait main.",
    img: "/assets/images/products/Sac-a-main-cuir-scaled.jpg",
    price: 170,
  },
  {
    id: 14,
    catégorie: "Tableau",
    title: "TABLEAU LETTRE",
    desc: "Personnalisez votre tableau avec une photo et une phrase touchante pour l’offrir comme un cadeau inoubliable.",
    img: "/assets/images/products/294417108_353476023655103_6127164178699476243_n-removebg-preview-1.png",
    price: 55,
  },
  {
    id: 15,
    catégorie: "Veilleuse",
    title: "VEILLEUSE 3D",
    desc: "Vous chercher à faire un cadeau personnalisé, une veilleuse décorative pour votre bureau ou maison? 3D Creativity vous propose les veilleuses 3D Led.",
    img: "/assets/images/products/Lampe-Led1-1.jpg",
    price: 50,
  },
  {
    id: 16,
    catégorie: "Veilleuse",
    title: "VEILLEUSE BTE",
    desc: "Veilleuse BTE : Veilleuse personnalisée, 3 face avec découpe de motif selon choix et une face avec gravure d’image. L’astuce de cette veilleuse est qu’elle est à l’allure d’une boite, et lors de l’ouverture de la boite, la veilleuse apparait .",
    img: "/assets/images/products/i2.png",
    price: 80,
  },
  {
    id: 17,
    catégorie: "Veilleuse",
    title: "VEILLEUSE CUBE",
    desc: "Veilleuse Cubique",
    img: "/assets/images/products/WhatsApp-Image-2022-12-27-at-09.31.43.jpeg",
    price: 35,
  },
];

export default DATA;
